[package]
name = "institution-registry"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-access = "=0.7.2"
stellar-macros = "=0.7.2"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
